// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: geometry-test.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#if CAPNP_VERSION != 9001
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif

#include "geometry.capnp.h"

CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(b1230cd98ee97fc4);

}  // namespace schemas
}  // namespace capnp

namespace fsc {

extern const ::capnp::_::ConstStruct< ::fsc::Mesh> TEST_CUBE;
// =======================================================================================

// =======================================================================================

}  // namespace

CAPNP_END_HEADER

