// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: magnetics-test.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#if CAPNP_VERSION != 9001
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif

#include "magnetics.capnp.h"

CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(f0487bad1c67dbb0);
CAPNP_DECLARE_SCHEMA(841e1c9017efec36);

}  // namespace schemas
}  // namespace capnp

namespace fsc {

extern const ::capnp::_::ConstStruct< ::fsc::ToroidalGrid> TEST_GRID;
extern const ::capnp::_::ConstStruct< ::fsc::MagneticField> WIRE_FIELD;
// =======================================================================================

// =======================================================================================

}  // namespace

CAPNP_END_HEADER

