[build-system]
requires = [
  "setuptools>=42",
  "setuptools_scm[toml]>=6.2",
  "scikit-build",
  "cmake",
  "numpy==1.19.5",
  "ninja; platform_system!='Windows'"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]